### ISSUE TITLE
CORS headers on all paths

### ISSUE THREAD

**Issue by smnmyr** [Interactions-HSG/ax12ctrl#11]
It should be sufficient to add the proper w.Header().Set("...", "...") with leubot's resources in robot.go and user.go

In Java, this would be something like:

corsHeaders.put(com.google.common.net.HttpHeaders.ACCESS_CONTROL_ALLOW_ORIGIN, Arrays.asList("*"));
corsHeaders.put(com.google.common.net.HttpHeaders.ACCESS_CONTROL_ALLOW_CREDENTIALS, Arrays.asList("true"));
corsHeaders.put(com.google.common.net.HttpHeaders.ACCESS_CONTROL_ALLOW_METHODS, Arrays.asList(HttpMethod.GET.name(), HttpMethod.POST.name(), HttpMethod.PUT.name(), HttpMethod.DELETE.name(), HttpMethod.HEAD.name(), HttpMethod.OPTIONS.name()));

(with the proper METHODS of course, where OPTIONS and HEAD should be present in all)

**Comment by iomz** [comment]
TODO:
- update the swagger
- update the version to v1.2.3

**Comment by iomz** [comment]
Will be closed after #14

**Comment by smnmyr** [comment]
OPTIONS requests currently return 400.

**Comment by smnmyr** [comment]
Those resources that require it (e.g., /wrist/angle) don't have PUT in the OPTIONS CORS preflight.
