### ISSUE TITLE
Provide feedback to clients when physical actions are completed

### ISSUE THREAD

**Issue by andreiciortea** [Interactions-HSG/ax12ctrl#7]
With the current leubot API, software clients cannot obtain the status of an action being performed (e.g., when the action is completed). One exception is deleting the current user: it seems the HTTP request blocks until leubot moves to the resting position.

So then the options would be: either use blocking requests for all actions that require time for completion (simplest way out), or otherwise keep non-blocking requests and design a feedback mechanism for clients. I would go for the latter and use a non-blocking request for deleting the current user as well.

**Comment by iomz** [comment]
Thanks for your comments.

PhantomX movement is unfortunately asynchronous; i.e., the ArmLink Serial doesn't provide an "upon completion" feedback, so the API cannot provide such things, either.

For `/user`, please send me the spec and open the new issue :-)
