### ISSUE TITLE
The user resource can be defined more precisely

### ISSUE THREAD

**Issue by andreiciortea** [Interactions-HSG/ax12ctrl#8]
A GET request to `/user` retrieves a representation of the current user, but when a POST request is received `/user` acts as a container. E.g., the URI returned in the `Location` header field with the response for creating a new user is:
`https://api.interactions.ics.unisg.ch/leubot/v1.2/user/a86(...)357`.

One alternative would be to define a container `/users/` and a resource `/users/current-user` for retrieving a representation of the current user.

Also, a POST request to `/user/` (with a trailing slash) will currently return a 503:

```
(base) Andreis-MacBook-Pro:~ andreiciortea$ curl -iL -X POST 'https://api.interactions.ics.unisg.ch/leubot2/v1.2/user/' \
> -H 'Content-Type: application/json' \
> -d '{"name" : "Andrei Ciortea", "email" : "andrei.ciortea@unisg.ch"}'
HTTP/1.1 301 Moved Permanently
Server: nginx/1.14.1
Date: Tue, 30 Jun 2020 19:15:21 GMT
Content-Length: 0
Connection: keep-alive
Location: /leubot2/v1.2/user

HTTP/1.1 503 Service Temporarily Unavailable
Server: nginx/1.14.1
Date: Tue, 30 Jun 2020 19:15:21 GMT
Content-Type: text/html
Content-Length: 213
Connection: keep-alive

<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>
```

**Comment by iomz** [comment]
User resource: practically, it is not possible to register multiple users for control – after all this user resource is created in order to manage a singleton resource (Leubot)

Trailing slash: it's a design decision from [gorilla/mux](https://github.com/gorilla/mux) and I also support that.

So not supporting this 🙏
